# Generated by Django 3.2 on 2022-05-10 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0003_auto_20220510_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mentioned_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_mentioned_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
