# Generated by Django 3.2 on 2022-05-19 09:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0010_commentvotes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvotes',
            unique_together={('creator', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postvotes',
            unique_together={('creator', 'post')},
        ),
    ]
